create table if not exists public.leaderboard_entries (
  id bigint generated by default as identity primary key,
  run_id uuid not null unique,
  player_name text not null check (char_length(player_name) between 2 and 24),
  damage_dealt bigint not null check (damage_dealt between 0 and 100000000),
  enemies_killed integer not null check (enemies_killed between 0 and 100000),
  survival_ms integer not null check (survival_ms between 0 and 1800000),
  character_id text not null check (character_id in ('haunted', 'the-penitent', 'ashwalker')),
  victory boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists leaderboard_entries_damage_idx
  on public.leaderboard_entries (damage_dealt desc, created_at asc);

create index if not exists leaderboard_entries_kills_idx
  on public.leaderboard_entries (enemies_killed desc, created_at asc);

create table if not exists public.run_analytics (
  id bigint generated by default as identity primary key,
  run_id uuid not null unique,
  player_name text check (player_name is null or char_length(player_name) between 2 and 24),
  character_id text not null check (character_id in ('haunted', 'the-penitent', 'ashwalker')),
  victory boolean not null default false,
  survival_ms integer not null check (survival_ms between 0 and 1800000),
  enemies_killed integer not null check (enemies_killed between 0 and 100000),
  damage_dealt bigint not null check (damage_dealt between 0 and 100000000),
  level_reached integer not null check (level_reached between 1 and 1000),
  souls_collected integer not null check (souls_collected between 0 and 100000000),
  run_summary jsonb not null check (
    jsonb_typeof(run_summary) = 'object'
    and octet_length(run_summary::text) <= 300000
  ),
  created_at timestamptz not null default now()
);

create index if not exists run_analytics_created_idx
  on public.run_analytics (created_at desc);

create index if not exists run_analytics_character_idx
  on public.run_analytics (character_id, created_at desc);

alter table public.leaderboard_entries enable row level security;
alter table public.run_analytics enable row level security;

grant usage on schema public to anon, authenticated;
revoke all on table public.leaderboard_entries from anon, authenticated;
revoke all on table public.run_analytics from anon, authenticated;
grant select on table public.leaderboard_entries to anon, authenticated;

grant usage on schema public to service_role;
grant select, insert on table public.leaderboard_entries to service_role;
grant select, insert on table public.run_analytics to service_role;
grant usage, select on sequence public.leaderboard_entries_id_seq to service_role;
grant usage, select on sequence public.run_analytics_id_seq to service_role;

drop policy if exists "Public leaderboard read" on public.leaderboard_entries;
create policy "Public leaderboard read"
  on public.leaderboard_entries
  for select
  to anon, authenticated
  using (true);

notify pgrst, 'reload schema';
