export const BALANCE = {
  maxMoveSpeedMultiplier: 2,
  maxCooldownReduction: 0.6,
  maxPickupRadiusMultiplier: 3,
  maxCritChance: 0.75,
  maxAreaMultiplier: 2.5,
  maxAttackSpeedMultiplier: 2.5,
  maxXpGainMultiplier: 2,
  maxThreatPowerBonus: 28,
  artifactRarityWeights: {
    common: 50,
    uncommon: 30,
    rare: 15,
    legendary: 5,
  },
  maxActiveChests: 2,
  maxActiveHazards: 30,
  maxActiveBuildings: 2,
  firstChestSpawnDelayMs: {
    min: 25000,
    max: 35000,
  },
  chestSpawnDelayMs: {
    min: 65000,
    max: 85000,
  },
  chestLifetimeMs: 60000,
  chestMinPlayerDistance: 280,
  chestMaxPlayerDistance: 480,
  maxThreatTier: 10,
  threatTierDurationMs: 90000,
  threatPowerScoreOffset: 8,
  threatPowerScorePerTier: 7,
  threatEvolvedWeaponScore: 3,
  threatHealthPerTier: 0.18,
  threatDamagePerTier: 0.06,
  maxCrimsonOrbitAxes: 5,
  maxCrimsonOrbitRadius: 200,
  maxCrimsonOrbitAxeSize: 76,
  minCrimsonOrbitHitCooldownMs: 420,
} as const;
